name: Run NSG Check
on: [pull_request]

jobs:
  NsgCheck:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Local GitHub Repo
        uses: actions/checkout@v3

      - name: Checkout Main branch for comparison of data
        uses: actions/checkout@v3
        with:
          ref: main
          path: main/

      - name: Checkout microsegmentation guidlines
        uses: actions/checkout@v3
        with:
          repository: officedepot/microsegmentation_guidelines
          token: ${{ secrets.CLOUD_ADMIN_GITHUB_TOKEN }}
          path: ./azure_nsg_review/microsegmentation_guidelines

      - name: run azure NSG checker
        uses: ./azure_nsg_review
        continue-on-error: true
        id: azure_nsg_review
        env:
          PULLNUMBER: ${{ github.event.pull_request.number }}
          GITSECRET: ${{ secrets.GITHUB_TOKEN }}
