---
name: Close inactive issues
on:
  schedule:
    - cron: "0 8 * * *"
# TEST
jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          ### Repo Default Information
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ### Issues
          days-before-issue-stale: 1
          stale-issue-message: "This issue is stale because it has been open for 1 days with no activity."
          days-before-issue-close: 2
          close-issue-message: "This issue was closed because it has been inactive for 2 days since being marked as stale."
          stale-issue-label: "stale"
          close-issue-label: "gha_close_stale"

          ### Pull Requests
          days-before-pr-stale: 1
          stale-pr-message: "This pull request is stale because it has been open for 1 days with no activity."
          days-before-pr-close: 2
          close-pr-message: "This pull request was closed because it has been inactive for 2 days since being marked as stale."
          stale-pr-label: "stale"
          close-pr-label: "gha_close_stale"
